# Generated by Django 3.0.1 on 2019-12-28 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=0, max_digits=10, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('qtype', models.CharField(max_length=50)),
                ('question', models.TextField()),
                ('question_image', models.ImageField(blank=True, upload_to='question')),
                ('difficulty', models.DecimalField(decimal_places=1, default=1000, max_digits=10)),
                ('hint', models.TextField(blank=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Category')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizes',
                'ordering': ('id',),
            },
        ),
    ]
