# Generated by Django 3.0.1 on 2020-01-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('category',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
