# Generated by Django 3.0.1 on 2020-01-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200128_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(help_text='a user friendly url', max_length=200)),
                ('random_order', models.BooleanField(default=False, help_text='Display the questions in a random order or as they set..')),
                ('max_questions', models.PositiveIntegerField(blank=True, help_text='Number of questions to be answered on each attempt.', null=True)),
                ('answers_at_end', models.BooleanField(default=False, help_text='Correct answer is NOT shown after question. Answers displayed at the end.')),
                ('exam_paper', models.BooleanField(default=False, help_text='IF yes, the result of each attempt by a user will be stored. Necessary for marking')),
                ('single_attempt', models.BooleanField(default=False, help_text='IF yes, only one attemptby a user will be permitted.')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Category')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizes',
            },
        ),
    ]
