# Generated by Django 3.0.1 on 2020-01-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20200130_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='figure',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
